$schema: https://fiboa.github.io/schema/v0.1.0/schema.json
required:
  - flik
properties:
  flik:
    type: string
    minLength: 16
    maxLength: 16
    pattern: ^[A-Z]{2}[A-Z0-9]{2}[A-Z0-9]{2}[A-Z0-9]{10}$